name: Version Bump and Create PR

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  versionBumpPR:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js and pnpm
      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      # Step 3: Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Step 4: Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install

      # Step 5: Bump the version using pnpm
      - name: Bump version
        run: pnpm version patch

      # Step 6: Create a new branch for the version bump
      - name: Create new branch
        run: |
          BRANCH_NAME="version-bump-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          git checkout -b $BRANCH_NAME
          git add package.json pnpm-lock.yaml
          git commit -m "chore: Bump version using pnpm"
          git push origin $BRANCH_NAME

      # Step 7: Create a Pull Request
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "chore: Bump version using pnpm"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          base: main
          title: 'chore: Bump version using pnpm'
          body: |
            This PR bumps the version in `package.json` and updates the lockfile using `pnpm version patch`.
          labels: |
            version bump
            automated pr
          draft: false
